In [2]:
import numpy1 as np
list1=[1,2,3,4]*2
print(list1)
arr1=np.array([1,2,3,4])*2
print(arr1)


[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [15]:
array=np.array([[[ 'A','B','C'],['D','E','F'],['G','H','I']],
               [[ 'J','K','L'],['M','N','O'],['P','Q','R']],
               [[ 'A','B','C'],['D','E','F'],['G','H','I']]])
print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)
print(array.itemsize)
print(array.data)
print(array[0][0][0])
print(array[0,0,1])
word=array[1,1,0]+array[0,0,0]+array[1,1,1]
print(word)

3
(3, 3, 3)
27
<U1
4
A
B
MAN


In [43]:
#slicing
array=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                 [13,14,15,16]])

#array[start:end:step]
#print(array[0])
print(array[::2])
print(array[:,-1])

print(array[:,::-2])
print(array[2:,1:3])
print(array[2:,2:])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[ 4  8 12 16]
[[ 4  2]
 [ 8  6]
 [12 10]
 [16 14]]
[[10 11]
 [14 15]]
[[11 12]
 [15 16]]


In [45]:
#arithmetic
#scalar

array=np.array([1,2,3])
print(array+1)
print(array-1)
print(array*2)
print(array/2)
print(array**3)

[2 3 4]
[0 1 2]
[2 4 6]
[0.5 1.  1.5]
[ 1  8 27]


In [49]:
#vectorized math functions
array=np.array([1,2,3])
print(np.sqrt(array))
print(np.log(array))
print(np.exp(array))
print(np.amax(array))
print(np.pi*array**2)

[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]
3
[ 3.14159265 12.56637061 28.27433388]


In [53]:
scores=np.array([60,70,75,80,90,98])
print(scores[scores>70])
scores[scores<70]=0
print(scores)
print(scores==80)
print(scores<=80)

[75 80 90 98]
[ 0 70 75 80 90 98]
[False False False  True False False]
[ True  True  True  True False False]


In [59]:
# broadcasting
#number of columns should match or have a 1
array1=np.array([[1,2,3,4]])
array2=np.array([[1],[2],[3]])
print(array1+array2)
print(array1*array2)
print(array1.shape)
print(array2.shape)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]
(1, 4)
(3, 1)


In [61]:
array1=np.array([[1,2,3,4,5,6,7,8,9,10]])
array2=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array1.shape)
print(array2.shape)

print(array1*array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [65]:
#Aggregate functions= summarize data and typically return a single value

array=np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))
print(np.sum(array,axis=0))
print(np.sum(array,axis=1))

55
5.5
2.8722813232690143
8.25
1
10
0
9
[ 7  9 11 13 15]
[15 40]


In [5]:
#Filtering= process of selecting elements from an array that match a given condition
ages=np.array([[20,21,22,14,18,16,15,25],
              [26,30,60,55,23,13,17,40]])
teenagers=ages[ages<18]
print(teenagers)

adults=ages[(ages>=18) & (ages<=50)]
print(adults)
seniors=ages[ages>50]
print(seniors)

adults=np.where(ages>=18,ages,0) #preserves original form of data
print(adults)


[14 16 15 13 17]
[20 21 22 18 25 26 30 23 40]
[60 55]
[[20 21 22  0 18  0  0 25]
 [26 30 60 55 23  0  0 40]]


In [10]:
#random numbers
rng=np.random.default_rng(seed=1)
print(rng.integers(low=1, high=101, size=(3,2)))
array=rng.integers(1,10,size=(3,3))
print(array)
array=rng.random((3,3))
print(array)

[[48 52]
 [76 96]
 [ 4 15]]
[[8 9 3]
 [3 8 4]
 [3 8 3]]
[[0.54959369 0.02755911 0.75351311]
 [0.53814331 0.32973172 0.7884287 ]
 [0.30319483 0.45349789 0.1340417 ]]


In [34]:
rng=np.random.default_rng()
names=np.array(["zach🚗","kev","dan","ian","jim"])
names=np.sort(names)
print(names)

name=rng.choice(names)
print(name)
names=rng.choice(names,size=(2,2))
print(names)

['dan' 'ian' 'jim' 'kev' 'zach🚗']
dan
[['ian' 'zach🚗']
 ['dan' 'kev']]


In [27]:
#np.random.seed(seed=1)
print(np.random.uniform(low=-1, high=1, size=(3,3)))
rng=np.random.default_rng()
#print(rng.uniform(low=-1, high=1, size=(3,3)))
array=np.array([1,2,3,4,5])
rng.shuffle(array)
print(array)

[[ 0.24734441  0.50188487 -0.30220332]
 [-0.46014422  0.79177244 -0.14381762]
 [ 0.92968009  0.326883    0.24339144]]
[3 5 4 2 1]
